### ISSUE TITLE
[Feature]: 초기 설정 완료 온보딩 화면 구현

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC3-Team7-MoTe#12]
### Feature 설명

초기 설정이 완료된 후 뜨는 온보딩 화면을 구현합니다.

<img width="250" alt="image" src="https://user-images.githubusercontent.com/75792767/179214814-ff16ddc5-18ad-48dc-9f8e-048a8ae24fca.png">

### Related View(Optional)

- ex. HomeViewController

### 우선순위

★★★★★

### 예상 작업 기간

~ 07/16(토)

**Comment by Chaeho-Min** [comment]
UIKit에서 SwiftUI 프리뷰 활용하기
- https://taekki-dev.tistory.com/21

**Comment by wody-d** [comment]
제가 정리한 건데 이것도 봐주세요~

https://github.com/wody-d/woody-iOS-tip/issues/14
