### ISSUE TITLE
[feature]: 도시선택 화면 구현

### ISSUE THREAD

**Issue by deslog** [DeveloperAcademy-POSTECH/MC3-Team7-MoTe#26]
### Feature 설명

미국과 캐나다는 도시별로 시간이 다르기 때문에 도시를 선택할 수 있는 화면을 구현합니다.

### 스크린샷

<img width="390" alt="image" src="https://user-images.githubusercontent.com/96969693/179396913-906da526-d816-4004-a912-bca80934cc24.png">

### 예상 작업 기간

0717~0718

**Comment by wody-d** [comment]
없어졌습니다.
