### ISSUE TITLE
Dynamic Types, 왜 고려해야 하죠?

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC3-Team7-MoTe#33]
'다이나믹 타입 적용 귀찮고 크게 쓸모도 없는 것 같은데 이 사람은 왜 자꾸 시키는거지?'라는 생각을 갖고 있을 수도 있을 것 같아서 제가 자꾸 고집부리는 이유를 알려드리려고 이슈를 적습니다.😛

제가 다이나믹 타입을 적용하는 이유는 두 가지입니다.

1. **가장 적용하기 쉽고, 가장 많은 사람들에게 필요한 접근성 요소라서.**
2. **유연한 레이아웃을 짜는데 최고의 연습방법이라서.**

## 1. 접근성(Accessibility)

다이나믹 타입을 적용하면 글자 크기를 사용자가 설정에서 키울 수가 있어 글자가 잘 안 보이는 분들에게 도움이 됩니다.  
특히, 저시력자 뿐만 아니라, 저희 부모님 세대만 되더라도 스마트폰의 화면이 작아서, 글자 크기를 키우는 것에 대한 니즈가 많습니다.   
따라서 생각보다 많은 사람들이 필요로 하기 때문에 웬만하면 적용할만한 접근성 요소라고 생각합니다 🙇‍♂️

## 2. 유연한 레이아웃 연습

어플에 자주 쓰이는 셀 형태를 기준으로 설명하겠습니다.  

개발 초기에 레이아웃을 동적으로 짜는 것에 익숙치 않거나, 하는 방법을 몰라서 고정값을 주는 경우가 많을 것입니다.  
그런데 고정값으로 개발했다가 이런 상황이 발생하면 어떨까요?

1. **디자이너가 문구나 컨텐츠 수정을 요청**
2. **화면 크기가 다른 기기에서 실행**

1번의 경우 수정된 컨텐츠로 인해 변한 높이와 너비를 확인하고, **고정값을 일일이 수정해줘야 합니다**.  
만약 애초에 내부 컨텐츠 크기에 따라 동적으로 셀 크기가 변하도록 레이아웃을 짰다면? **변경되는 컨텐츠나 문구만 수정해주면 끝날 것입니다**.  

<img width="300" alt="image" src="https://user-images.githubusercontent.com/75792767/179465528-c683c976-2d54-4086-8dea-bfc14ba3d3c6.png">

'목표일의 전화 시간에 알림을 보냅니다.' 문구를 수정하게 되어 두 줄로 넘어가게 됐을 때, 셀 높이를 고정값으로 줬다면 그 값도 변경해줘야 할 것입니다. 그러나 상하 패딩값을 주어 유연하게 변할 수 있도록 설정해놨다면, 코드에서 문구만 수정하면 셀이 알아서 높아질 것입니다.

2변의 경우 SwiftUI로 개발할 때, 뷰에 .frame으로 고정값을 주어서 아이폰 13이 아닌 다른 기기로 봤을 때 되게 이상하게 나와서 고생한 경험이 다들 있을 것입니다.  
특히 어플 다 만들고나서 이 고정값들을 뜯어고치려고 하면 매우 막막해지죠.

그래서 저는 아예 처음부터 레이아웃에 고정값을 최소화해야 한다고 생각합니다.  
다이나믹 타입을 적용하면, 디자이너가 수정사항을 주지 않아도 내부 컨텐츠 크기가 **무조건** 변하게 됩니다.  
따라서 어플 개발 초기부터 너비나 높이에 고정값을 주지 않고 갈 수 있게 되죠. 이건 엄청난 이득이라고 생각합니다! 🤑

## 결론

- **접근성 향상** 뿐만 아니라, 어플의 반응형 화면을 초기부터 설계하게 해주어 **추후 수정사항에 대한 유지보수를 쉽게 만든다**.
- 반응형 레이아웃을 짜는 것이 **습관화**된다.

**Comment by Lim-YongKwan** [comment]
저도 레이아웃에 고정값을 최소화 시키는게 맞다고 봅니다!
만일 숫자를 써야 하는 일이 있다면 minWidth 나 maxWidth 와 같이 다른 상황을 고려할 수 있는 값으로 주는게 맞다고도 생각합니다.
앱 출시를 목적으로 하고 있는 만큼 Dynamic Types 공부를 하는겸 이와 같은 요소를 계속해서 고려하면서 가는게 맞다고 봅니다!
다들 귀찮더라도 화이팅!

**Comment by deslog** [comment]
autolayout이 익숙하지 않은 저한테는 정말 좋은기회인것 같아요! 정말 출시까지 화이👍
