### ISSUE TITLE
[feature]: 기록 화면 달력 추가

### ISSUE THREAD

**Issue by deslog** [DeveloperAcademy-POSTECH/MC3-Team7-MoTe#34]
### Feature 설명

- [ ] 기록탭에서 사용할  달력을 구현합니다..

우선 디자인과 스크롤과 같은 것들을 고려하지 않은 채로 달력만 우선 구현합니다.

### 스크린샷

확정된 모습은 아니지만, 이런 형태의 달력일 것 같습니다. 

<img width="250" alt="image" src="https://user-images.githubusercontent.com/96969693/179509898-e62d1546-e99c-473e-b466-8acbe603e45f.png">

### 예상 작업 기간

0718~0720

**Comment by deslog** [comment]
7월 19일 회의 결과 해당 이슈도 일단 보류합니다! 👀

**Comment by wody-d** [comment]
보류니까 close할게요.
