### ISSUE TITLE
[MUST READ] 코딩 컨벤션 

### ISSUE THREAD

**Issue by wody-d** [DeveloperAcademy-POSTECH/MC3-Team7-MoTe#4]
## 코딩 컨벤션 링크

이 swift coding convention은 스타수 377개로 가장 많이 쓰이는 컨벤션입니다. 이 컨벤션을 사용할 예정이라 프로젝트에 코드 작성하기 전에 꼭 한번씩 읽어보시구 아래 닉네임에 체크 부탁합니다. 

https://github.com/StyleShare/swift-style-guide 

- [x] Avo
- [x] Brown
- [x] Grizzly
- [x] Wonny
- [x] Woody

**Comment by wody-d** [comment]
@wody-d @wonny1012 @Chaeho-Min @deslog @Lim-YongKwan

**Comment by Chaeho-Min** [comment]
질문 있습니다. StyleShare 가이드에서는 가능하다면 변수를 정의할 때 함께 초기화하라고 나와있는데, 오늘 정한 코드 구조에서는 attribute() 메서드로 전부 빼놓기로 한 부분이 다른 것 같습니다.
이런 경우에는 팀에서 정한 컨벤션을 우선하여 작성하는게 맞을까요?

<img width="718" alt="image" src="https://user-images.githubusercontent.com/75792767/178719558-c2230917-41d8-44e1-8b51-ddb3da2b46e7.png">

StyleShare 가이드 부분. 참고로 then은 외부 프레임워크

<img width="525" alt="스크린샷 2022-07-13 오후 8 06 40" src="https://user-images.githubusercontent.com/75792767/178719786-cdd3c6a2-8e77-415c-9c61-79e65e93aed1.png">

오늘 팀에서 정한 UIViewController 구조

**Comment by Chaeho-Min** [comment]
<img width="606" alt="스크린샷 2022-07-13 오후 8 50 03" src="https://user-images.githubusercontent.com/75792767/178727052-f4d345f0-746b-4364-ba19-1c449f84a76f.png">
그리즐리의 의문 출처

**Comment by wody-d** [comment]
@Chaeho-Min 
attribute는 가능하다면 변수를 정의할 때 초기화하는 styleshare convention에 따르는 것이 좋을 듯 합니다. 하지만 storyboard를 사용할 경우 `cornerRadius`와 같은 attribute를 스토리보드상에서 줄 수 없을 수 있기 때문에 attribute 메소드가 생긴 것 같습니다. 저희가 뷰를 storyboard와 코드로 혼용해서 작성하기 때문에 이러한 혼동이 온 것 같습니다. 그래서 아래와 같이 따르면 될 것 같습니다. 

---- 

storyboard를 사용하여 뷰를 작성할 경우, attribute 메소드로 빼서 관리합니다.
```swift
func attribute() {
  setupButton()
  setupLabel()
}

func setupButton() { }

func setupLabel() { }
```

code로 작성할 경우, 변수를 정의할 때 attribute를 주기로 합니다.
```swift
let button: UIButton = {
  return $0
}(UIButton())
```

**Comment by wody-d** [comment]
@Lim-YongKwan 
1.
StyleShare에서만 클래스와 구조체 내 self의 명시적 사용을 지향하고 다른 컨벤션에서는 지양하라고 나와있습니다. 저도 아보와 같은 이유로 안 써오긴 했지만, StyleShare 컨벤션을 따르기로 했고 저희가 따로 논의하지 않았다면 사용해야 된다고 생각합니다..! 지금 논의해볼까요? 전 "안 써도 된다"에 찬성합니다.

[StyleShare](https://github.com/StyleShare/swift-style-guide)
| 클래스와 구조체 내부에서는 self를 명시적으로 사용합니다.

[Raywenderlich](https://github.com/raywenderlich/swift-style-guide)
| For conciseness, avoid using self since Swift does not require it to access an object's properties or invoke its methods.

[Airbnb 코딩 컨벤션](https://github.com/airbnb/swift#omit-self)
| Don't use self unless it's necessary for disambiguation or required by the language.

[LinkedIn 코딩 컨벤션](https://github.com/linkedin/swift-style-guide)
| 3.1.11 Prefer not writing self. unless it is required.

2.
MARK와 같은 경우 아보의 의견과 같습니다. 주석은 최대한 쓰지 않고 프로퍼티와 메소드의 네이밍으로 판단하게끔 하는 것이 가장 좋은 것 같습니다.

**Comment by deslog** [comment]
**앞에서 논의하고자 하는 내용**
- self를 꼭 써야하는가? 
  - 저도 self는 코드의 가독성을 떨어뜨린다는 것에 동의합니다. 그리고 아보처럼.. 굳이 안써도되는데 왜씀? 에 동의하기때문에 안쓰는것에 동의합니다~!

**질문 있습니다.**

- ```빈 줄에는 공백이 포함되지 않도록 합니다.```
xcode에서 코드를 작성하다가 엔터를 치면 앞에 공백이 생길 수밖에 없는데,,, 이 경우도 제외할지 말지 논의해보는게 좋을 것 같습니다. (사실 별로 신경쓰지 않는 거의 무시해도 되는 컨벤션아닌가요..?!)
<img width="458" alt="image" src="https://user-images.githubusercontent.com/96969693/178769337-0ff8579e-0037-4dae-8ff8-bc12fddbf333.png">

**Comment by wody-d** [comment]
그럼 self는 쓰지 않는 것으로 해요. 
빈 줄에 공백이 포함되지 않도록 하는 경우에는 [이 링크](https://stackoverflow.com/questions/57049920/how-to-fix-trailing-whitespace-violation-warnings-caused-by-swiftlint-in-xcode)를 참고해서 Xcode Preferences에서 설정하시면 좋을 듯 합니다. 설정하시고 cmd + I 를 해주면 공백이 사라집니다.
