### ISSUE TITLE
[SETTING] auto-assign 설정

### ISSUE THREAD

**Issue by deslog** [DeveloperAcademy-POSTECH/MC3-Team7-MoTe#5]
## Description
pr을 날릴때 자동으로 reviewer를 추가해주는 auto-assign을 적용합니다.

## 스크린샷
<img width="300" alt="image" src="https://user-images.githubusercontent.com/96969693/178633762-e0447677-84d9-4cea-8469-a91c242e4b6e.png">

## ETC
https://github.com/apps/auto-assign

**Comment by wody-d** [comment]
이게 무슨 기능인가요?
