### ISSUE TITLE
[feature]: 목표 레이아웃 디자인 재수정

### ISSUE THREAD

**Issue by Lim-YongKwan** [DeveloperAcademy-POSTECH/MC3-Team7-MoTe#70]
### Feature 설명

목표 설정 온보딩 부분 레이아웃 재 수정.

### 예상 작업 기간

~07/26(화)

**Comment by Chaeho-Min** [comment]
CoreData 작업으로 바쁜 그리즐리를 위해 제가 맡기로 했습니다~
- #86
